#!/bin/bash
scriptdir="/home/sid/thesis_SidReed/scripts"
fps="$1"
genusname="$2"
echo "preping sequences"
"$scriptdir"/prepSeqs.sh "$fps" "$genusname"
echo "all vs all alingment"
"$scriptdir"/diamondAlign.sh "$genusname"
cd "$genusname"
echo "single link clustering to gene families"
python "$scriptdir"/single_link_clustering_blast_hits.py allvsallproteins.dmnd.out all_proteins.faa "$genusname"
echo "creating PA matrix"
python "$scriptdir"/createPAMatrix.py gene_families_"$genusname".json protein_fastas/ "$genusname"
echo "building species trees"
python "$scriptdir"/build_species_tree.py pa_matrix_"$genusname".npy column_indexes_families_"$genusname".json gene_families_"$genusname".json all_nucleotides.fna "$genusname"
echo "building gene trees"
python "$scriptdir"/generate_gene_trees.py pa_matrix_"$genusname".npy column_indexes_families_"$genusname".json gene_families_"$genusname".json all_nucleotides.fna "$genusname"
python "$scriptdir"/build_network_from_trees.py ../"$genusname"
